name: Full CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # -------------------------
      # Backend Build (Maven)
      # -------------------------
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build Backend JAR
        run: mvn -B -DskipTests package --file EmployeeDemo/pom.xml

      # -------------------------
      # Docker Login
      # -------------------------
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # -------------------------
      # Build & Push Backend Image
      # -------------------------
      - name: Build Backend Image
        run: docker build -t jayeshjain11/backend:latest ./EmployeeDemo

      - name: Push Backend Image
        run: docker push jayeshjain11/backend:latest

      # -------------------------
      # Build & Push Frontend Image
      # -------------------------
      - name: Build Frontend Image
        run: |
          docker build \
            --build-arg REACT_APP_API_BASE_URL=http://backend:8080 \
            -t jayeshjain11/frontend:latest ./employee-frontend

      - name: Push Frontend Image
        run: docker push jayeshjain11/frontend:latest

